export const mockData = [
    {
      
       "id": "f9be707a-714d-4fd0-ac73-9d070fd2c033",
        "title": "Cooling and Freezing Equipment Operator",
        "description": "Sunt ut aliquam iure vel. Fuga voluptatem debitis rem nihil vel. Et consequatur sapiente quia voluptatibus aliquid. Est quas sapiente adipisci aut aut consequatur.",
        "company": "Hudson, Wiegand and Shields",
        "location": "Talisay, Chile",
        "salary_from": 75568,
        "salary_to": 84827,
        "employment_type": "Consultant",
        "application_deadline": "Wed, 07/16/2003",
        "qualifications": "[\"3+ years in Python\",\"Skilled in React\",\"Expert in Java\",\"Skilled in GraphQL\"]",
        "contact": "139-253-685",
        "job_category": "Mobile App Developer",
        "is_remote_work": 0,
        "number_of_opening": 8,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
      },
      {
        "id": "f5711a36-e538-4e88-872c-bac8f9300a76",
        "title": "Patternmaker",
        "description": "Consequatur velit rerum sint ab. Nobis distinctio ut ex hic et ea. Harum et magni perferendis eius impedit hic.",
        "company": "Botsford, Schuster and Botsford",
        "location": "Sorsogon City, Georgia",
        "salary_from": 63029,
        "salary_to": 115558,
        "employment_type": "In-house Developer for Non-Tech Company",
        "application_deadline": "Sun, 08/22/2021",
        "qualifications": "[\"Advanced HTML\\/CSS\",\"Master of TypeScript\",\"5 years in PHP\",\"3+ years in Angular\"]",
        "contact": "200-283-561",
        "job_category": "DevOps Engineer",
        "is_remote_work": 1,
        "number_of_opening": 7,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
      },
      {
        "id": "9d4593e2-4539-44fc-a286-825072415d79",
        "title": "Plating Machine Operator",
        "description": "Aut sint nesciunt quia ea et. Earum sed fuga qui qui. Possimus sunt ea dolores voluptatem.",
        "company": "Kuhic-Kreiger",
        "location": "Cebu City, Azerbaijan",
        "salary_from": 56239,
        "salary_to": 104339,
        "employment_type": "Intern Developer",
        "application_deadline": "Sun, 07/30/2017",
        "qualifications": "[\"Skilled in React\",\"3 years in Node.js\",\"Solid understanding of AWS\",\"2 years in Vue.js\"]",
        "contact": "049-509-262",
        "job_category": "Front-end Developer",
        "is_remote_work": 1,
        "number_of_opening": 4,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
      },
      {
        "id": "ba803536-f24a-4ad8-a2d0-44e35e2a7195",
        "title": "Immigration Inspector OR Customs Inspector",
        "description": "Cumque velit natus quia quae optio nemo ut. Consequuntur et facere corporis numquam enim. Nam et et incidunt aliquam qui animi sit.",
        "company": "Schroeder, Bailey and Rempel",
        "location": "Cebu City, Korea",
        "salary_from": 72741,
        "salary_to": 97730,
        "employment_type": "Temporary Developer",
        "application_deadline": "Sat, 12/31/1983",
        "qualifications": "[\"Skilled in React\",\"Proficient in Kotlin\",\"Expert in Docker\",\"Proficient in MongoDB\"]",
        "contact": "128-855-902",
        "job_category": "DevOps Engineer",
        "is_remote_work": 1,
        "number_of_opening": 1,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
      },
      {
        "id": "15c99db6-0073-4d3f-ae99-2ac41058e447",
        "title": "Recyclable Material Collector",
        "description": "Non sint molestiae est sed. Quo deserunt qui occaecati labore ullam ipsum. Deserunt aspernatur incidunt facilis quia aut et.",
        "company": "Carroll Ltd",
        "location": "Angeles, Nepal",
        "salary_from": 69061,
        "salary_to": 111700,
        "employment_type": "Consultant",
        "application_deadline": "Fri, 03/25/2016",
        "qualifications": "[\"3 years in Node.js\",\"Expert in Java\",\"Solid understanding of AWS\",\"2 years in Vue.js\"]",
        "contact": "214-086-130",
        "job_category": "Back-end Developer",
        "is_remote_work": 0,
        "number_of_opening": 2,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
      },
      {
        "id": "5aff12b0-80b5-4dc7-b31d-9fcb18a4a4a4",
        "title": "Precision Lens Grinders and Polisher",
        "description": "Id quia est voluptas. Consectetur iusto quae molestiae asperiores. Vitae eum numquam et rem perspiciatis. Qui saepe illum natus praesentium aut aspernatur.",
        "company": "Medhurst-Leuschke",
        "location": "Tandag, Malta",
        "salary_from": 61127,
        "salary_to": 107887,
        "employment_type": "Part-time Developer",
        "application_deadline": "Wed, 07/20/2005",
        "qualifications": "[\"Skilled in React\",\"Master of TypeScript\",\"5 years in PHP\",\"Proficient in MongoDB\"]",
        "contact": "332-758-619",
        "job_category": "DevOps Engineer",
        "is_remote_work": 1,
        "number_of_opening": 9,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
      },
      {
        "id": "ae74be12-b7c5-42ea-b5fa-731affdfc6ae",
        "title": "Fiberglass Laminator and Fabricator",
        "description": "Eius enim voluptatem exercitationem dolores temporibus. Pariatur error nulla ducimus excepturi est. Earum labore unde reiciendis et impedit.",
        "company": "Braun and Sons",
        "location": "Lucena, French Southern Territories",
        "salary_from": 70182,
        "salary_to": 94662,
        "employment_type": "Co-founder/Technical Partner",
        "application_deadline": "Sun, 11/27/2005",
        "qualifications": "[\"Expert in JavaScript\",\"3+ years in Python\",\"2 years of Git experience\",\"2+ years in Ruby\"]",
        "contact": "198-928-875",
        "job_category": "Security Engineer",
        "is_remote_work": 1,
        "number_of_opening": 9,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
      },
      {
        "id": "96993fff-8581-4930-85f2-25d7dda101c6",
        "title": "Admin",
        "description": "Nisi quis aut distinctio qui magni ea dolores. Ut beatae cum perspiciatis qui id corrupti. Qui ea et exercitationem esse assumenda.",
        "company": "Anderson Group",
        "location": "Baguio, Argentina",
        "salary_from": 64217,
        "salary_to": 82115,
        "employment_type": "Intern Developer",
        "application_deadline": "Sat, 12/03/2005",
        "qualifications": "[\"4+ years in C++\",\"3+ years in Angular\",\"Expert in Docker\",\"2 years in Vue.js\"]",
        "contact": "914-598-532",
        "job_category": "Data Scientist",
        "is_remote_work": 0,
        "number_of_opening": 9,
        "created_at": "Sun, 10/15/2023",
        "updated_at": "Sun, 10/15/2023"
      
}
    ]